### ISSUE TITLE
node:14724) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be 

### ISSUE THREAD

**Issue by InvertedX** [nuxt/express#40]
```{r, error = TRUE} 
> backpack dev

(node:14724) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.


 DONE  Compiled successfully in 1633ms                                                                               12:48:45 AM
module.js:472
    throw err;
    ^

Error: Cannot find module 'F:\OP\My blog\"F:\OP'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

```

getting these errors when trying to run `npm run dev`

**Comment by InvertedX** [comment]
did you guys checked this template on any windows system 
i m running on windows  10 , tried both npm and yarn

1. NPM  v3.10.6
2. Node v7.9.0
3. Yarn  v0.23.2

**Comment by pangaunn** [comment]
I can run it normally

windows 10
npm 3.10.10
node 6.9.5

**Comment by InvertedX** [comment]
```{r,error = TRUE}
(node:7580) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
i solved this by upgrading babel-eslint. other one is still there.
i tried to build the project and it worked but dev command still throwing that module not found exception

**Comment by InvertedX** [comment]
is there any way to replace backpack with standard webpack

**Comment by Atinux** [comment]
Hi @InvertedX 

This is only a template, you can change backpack to a standard webpack template of course.

I can run the project perfectly on my computer. Can you try to upgrade to npm 5? It should fix the probem.

**Comment by InvertedX** [comment]
```
Error: Cannot find module 'F:\Opensource\nuxt\"F:\Opensource'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3 ```

i don't know what happening but i reinstalled my os and tried with latest npm (5) but i still getting this error in dev .. build is fine . i think something is not working with  backpack . now i have to try docker .
